DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password CHAR(256) NOT NULL,
    config_yaml TEXT NOT NULL
)