#
# Configuration file for API Gateway
#

connections:
  - host: localhost
    port: 8080
    routes:
      - path: /products
        upstream:
          name: product_service
          port: 9001
        rate-limit:
          zone: 10
          rate: 5
        auth:
          basic: false
          jwt: false

      - path: /orders
        upstream:
          name: order_service
          port: 9002
        rate-limit:
          zone: 10
          rate: 5
        auth:
          basic: false
          jwt: false
          
      - path: /protected
        upstream:
          name: protected_service
          port: 9003
        rate-limit:
          zone: 10
          rate: 5
        auth:
          basic: true
          jwt: false

      - path: /jwt
        upstream:
          name: jwt_service
          port: 9004
        rate-limit:
          zone: 10
          rate: 5
        auth:
          basic: false
          jwt: true