#
# Configuration file for API Gateway
#

connections:
  - host: localhost
    port: 8080
    routes:
      - path: /products
        upstream:
          name: product_service
          port: 9001

      - path: /orders
        upstream:
          name: order_service
          port: 9002

      - path: /test
        upstream:
          name: test_service
          port: 9003
