name: CI

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-go@v6.1.0
      - name: Run Unit Tests
        run: make unit-tests