name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - "docs/"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-go@v6.1.0
      - name: Run Unit Tests
        run: make unit-tests

  test-dataplane:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-go@v6.1.0
      - name: Create .env file
        run: |
          cat <<EOF > .env
          HTPASSWD_USER=${{ secrets.HTPASSWD_USER }}
          HTPASSWD_PASS=${{ secrets.HTPASSWD_PASS }}
          EOF
      - name: Test NGINX with microservices
        run: make test-docker
